version: '3.7'
  
services:
  react-dev:
    container_name: react-dev
    tty: true
    stdin_open: true
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - "./front:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development

  web:
    build: ./pse
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pse:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: