version: '3.7'
  
services:
  react-prod:
    container_name: react-prod
    build:
      context: front
      dockerfile: dockerfile-prod
    ports:
      - "80:80"

  web:
    container_name: web
    build: ./pse
    command: python pse/manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - mongodb

  migration:
    build: ./pse
    command: python pse/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - mongodb
    
  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data: