version: '3.7'
  
services:
  react-prod:
    container_name: react-prod
    build:
      context: front
      dockerfile: dockerfile-prod
    ports:
      - "80:80"

  web:
    container_name: web
    build: ./pse
    command: python pse/manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - mongodb

  migration:
    build: ./pse
    command: python pse/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - mongodb
    
  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
  
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - cluster.name=demo-es
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: 
      - 9300:9300
      - 9200:9200
    volumes:
      - elastic_data:/data/search


volumes:
  mongodb_data:
  elastic_data: