# Generated by Django 2.2.12 on 2020-04-26 19:41

from django.db import migrations, models
import djongo.models.fields
import engine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('pages', djongo.models.fields.ArrayField(model_container=engine.models.Page, model_form_class=engine.models.PageForm)),
            ],
        ),
    ]
