# Generated by Django 2.2.12 on 2020-05-04 19:19

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import engine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('pages', djongo.models.fields.ArrayField(model_container=engine.models.Page, model_form_class=engine.models.PageForm)),
            ],
        ),
        migrations.CreateModel(
            name='ElasticPage',
            fields=[
                ('name', models.CharField(max_length=210, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('num', models.IntegerField()),
                ('text', models.TextField()),
                ('doc_name', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Document')),
            ],
        ),
    ]
