# Generated by Django 2.2.12 on 2020-04-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisionResponse',
        ),
    ]
